### ISSUE TITLE
Refresh file after async job finishes

### ISSUE THREAD

**Issue by fedemp** [hauleth/asyncdo.vim#12]
Hi. I'm currently using your plugin with [`eslint`](https://eslint.org/). I have in my `ftplugin` for javascript, `autocmd! BufWritePost <buffer> AsyncDo eslint -f compact %`.

I would like to use the `--fix` option for eslint, but I would need to use call `:e %` or `:checktime` after the job finishes. Is it possible?

**Comment by hauleth** [comment]
It would be possible, but I will not implement it as asynchronous modification of the file is dangerous. Instead I suggest you to use `:make` to achieve such or use wrapper script as `equalprg`. If you really want to have something like that you can use:

```
autocmd! BufWritePost <buffer> exec 'AsyncDo eslint -f compact %' | e!
```
