### ISSUE TITLE
<cword> as argument no longer works as expected

### ISSUE THREAD

**Issue by igemnace** [hauleth/asyncdo.vim#13]
I have a `:Grep` command defined in my config as follows:

```
command! -bang -nargs=+ Grep call asyncdo#run(<bang>0, &grepprg, <f-args>)
```

I also have a convenience map for running `:Grep` with the word under the cursor, as follows:

```
nnoremap <Plug>GrepStar :Grep <lt>cword><CR>
```

I've started to notice that my `<Plug>GrepStar` map no longer works, providing the following error:

```
Error detected while processing function <lambda>8[1]..<SNR>91_finalize:
line   10:
E40: Can't open errorfile /tmp/v9JNAQ2/1
```

After a bit of debugging, I've identified that it worked before [this commit][1], but not after. It seems like the encompassing `expand()` [here][3] was needed to expand `<cword>` into the word under the cursor. Without it, a literal `<cword>` is passed to my `&grepprg`. True enough, `echom string(l:spec)` after [this line of the code][2] shows a seemingly mangled shell redirection:

```
['/bin/zsh', '-c', 'rg --vimgrep --no-heading <cword>>/tmp/vLnYX0b/2 2>&1']
```

I've prepared a patch reintroducing the required `expand()`, which solves this issue after some testing on my end.

[1]: https://github.com/hauleth/asyncdo.vim/commit/b62de9d38a2d8ff0f846de4c6c0ed766f5f5f332
[2]: https://github.com/hauleth/asyncdo.vim/blob/fffa0744cf555655ed4dae254e55cb2beb963285/autoload/asyncdo.vim#L50
[3]: https://github.com/hauleth/asyncdo.vim/commit/b62de9d38a2d8ff0f846de4c6c0ed766f5f5f332#diff-98dc729fd967bb69d6836c039cf7e4cfL36

**Comment by hauleth** [comment]
Thanks for your work. Merged.
